#!/usr/bin/env bash
# Checking if the number of arguments is less than 4
if [ "$#" -lt 3 ]; then
        echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

# Assigning arguments to variables
PATH_TO_FILE="$1"
IP_RECEIVER="$2"
USERNAME_RECEIVER="$3"
PATH_TO_SSH_KEY="$4"

# Transferring file using scp
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME_RECEIVER"@"$IP_RECEIVER":~/

