#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get install -y nginx

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a default index.html file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'

# Restart nginx
sudo service nginx restart


