#!/usr/bin/env bash
# Install Nginx web server
sudo apt-get update
sudo apt-get install -y nginx

ufw allow 'Nginx HTTP'

redirect_me="http {
    server {
        listen 80;
        server_name  localhost;
        location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;

    }
}"
sed -i "s/server_name  localhost;/server_name  localhost;\n$redirect_me/g" /etc/nginx/sites-available/default
service nginx restart