#!/usr/bin/env bash
# Install Nginx web server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
redirect="http {\n
	server {\n
		listen        80;\n
		server_name   localhost 127.0.0.1;\n
		location /redirect_me/ {\n
			return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n
		}\n
	}"
sed -i "s/http {/$redirect/" /etc/nginx/nginx.conf
service nginx start