#!/usr/bin/env bash
# Installs nginx server on the server
# and sets up a custom 404 page and a custom header
sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page." > /var/www/html/404.html
service nginx start
echo "server {
    listen 80;
    root /var/www/html;
    add_header X-Served-By $HOSTNAME;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    error_page 404 /404.html;

    location / {
        try_files $uri $uri/ =404;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=9t9Mp0BGnyI;

    }
}" > /etc/nginx/sites-available/default

service nginx restart