#!/usr/bin/env bash
# Installs nginx server on the server
# and sets up a custom 404 page and a custom header
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page." > /var/www/html/404.html
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /var/www/html;
    index index.html index.htm;
    server_name _;
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }
    location /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=9t9Mp0BGnyI;

    }
}" > /etc/nginx/sites-available/default

service nginx restart