#!/usr/bin/env bash
# Installs Nginx server on the server
# and sets up a custom 404 page and a custom header

# Update package information
sudo apt-get update

# Install Nginx
sudo apt-get -y install nginx

# Allow Nginx HTTP traffic
sudo ufw allow 'Nginx HTTP'

# Create custom index.html and 404.html files
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page." > /var/www/html/404.html

# Configure Nginx
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By \$HOSTNAME;
    root /var/www/html;
    index index.html index.htm;
    server_name _;

    error_page 404 /404.html;

    location /404 {
        internal;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me/ {
        return 301 https://www.youtube.com/watch?v=9t9Mp0BGnyI;
    }
}
EOF

# Reload Nginx configuration
sudo systemctl reload nginx

# Print a success message
echo "Nginx server installed and configured successfully."
