#!/usr/bin/env bash
# Installs HAproxy on the server and sets up a load balancer
sudo apt-get update
sudo apt-get -y install haproxy
echo "
global
    log /dev/log local0  # Log to syslog
frontend http_front
    bind *:80
    timeout client 50000ms
    default_backend http_back
backend http_back
    timeout connect 5000ms
    timeout server 50000ms
    mode http
    server server1  35.174.184.151
    server server2  54.157.180.166" > test.conf
sudo haproxy -f test.conf