#!/usr/bin/env bash
# Installs HAproxy on the server and sets up a load balancer
sudo apt-get update
sudo apt-get -y install haproxy
cp -a /etc/haproxy{,.bak}
echo -e "
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server   267497-web-01  35.174.184.151:80 check
    server   267497-web-02  54.157.180.166:80 check" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
sudo haproxy restart

