#!/usr/bin/env bash
# Installs HAproxy on the server and sets up a load balancer
sudo apt-get update
sudo apt-get -y install haproxy
echo "
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server   267497-web-01  35.174.184.151 check
    server   267497-web-02  54.157.180.166 check
ENABLED=1" > test.conf
sudo haproxy -f test.conf