#!/usr/bin/env bash
# Assign the provided password to a variable
MYSQL_ROOT_PASSWORD=$1

# Define the filename format based on the current date
FILENAME=$(date +%d-%m-%Y).tar.gz

# Create a MySQL dump of all databases and compress it
mysqldump -uroot -p"$MYSQL_ROOT_PASSWORD" --all-databases > backup.sql
tar -czf "$FILENAME" backup.sql
