#!/usr/bin/env bash

# Check if a password is provided as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <MySQL root password>"
    exit 1
fi

# Assign the provided password to a variable
MYSQL_ROOT_PASSWORD=$1

# Define the filename format based on the current date
FILENAME=$(date +%d-%m-%Y).tar.gz

# Create a MySQL dump of all databases and compress it
mysqldump -u root -p"$MYSQL_ROOT_PASSWORD" --all-databases > backup.sql && tar -czf "$FILENAME" backup.sql
