#!/usr/bin/env bash
# A Bash scrit that manages manage_my_process.

Arg=$1

if [[ $Arg == "start" ]]
then
    ./manage_my_process &
    echo "$$" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [[ $Arg == "stop" ]]
then
    kill "$(pgrep -f /manage_my_process)" 
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [[ $Arg == "restart" ]]
then
    kill "$(pgrep -f /manage_my_process)" 
    rm /var/run/my_process.pid
    ./manage_my_process &
    echo "$$" > /var/run/my_process.pid
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
