#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
#   Only displays the username, user id, and user home directory path.
file="/etc/passwd"

while IFS=: read -r username _ uid _ _ home _
do
    echo "$username:$uid:$home"

done < "$file"


