#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# Your script should only display:

# username
# user id
# Home directory path for the user
# Requirements:

# You must use the while loop (for and until are forbidden)
# shellcheck disable=all
file="/etc/passwd"

while IFS=: read -r username x uid gid gecos home shell
do
    echo "$username:$uid:$home"

done < "$file"


