#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
# Requirements:
# You must use the until loop (for and while are forbidden)

count=0

until [ $count -gt 9 ]
do
    echo "Best School"
    ((count++))
done