#!/usr/bin/env bash
# 4. Write a Bash script that displays Best School 10 times.
i=0
while [ $i -le 10 ]
do
    if [ $i -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$((i+1))
done