#!/usr/bin/env bash
# 6. Write a Bash script that displays numbers from 1 to 20.
    # Displays 4 and then Bad luck from China for the 4th loop iteration
    # Displays 9 and then Best School for the 9th loop iteration
    # Displays 17 and then bad luck from Japan for the 17th loop iteration
#Requirements:
    #You must use the while loop (for and until are forbidden)
    #You must use the if statement (case is forbidden)

i=1
while [ $i -le 20 ]
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "Best School"
            ;;
        17)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        *)
            echo "$i"
            ;;
    esac
    i=$((i+1))
done