#!/usr/bin/env bash
# Wrte a Bash scrpt that dsplays the tme for 12 hours and 59 mnutes:

# dsplay hours from 0 to 12
# dsplay mnutes from 1 to 59
# Requrements:

# You must use the whle loop (for and untl are forbdden)

Hour=0
while [ $Hour -le 12 ]
do
    echo "Hour: $Hour"
    minutes=1
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        ((minutes++))
    done
    ((Hour++))
done