#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:

# display hours from 0 to 12
# display minutes from 1 to 59
# Requirements:

# You must use the while loop (for and until are forbidden)

hour=0
echo "Hour: $hour"
while [ $hour -le 11 ]
do
    minutes=1
    while [ $minutes -le 60 ]
        do
            if [ $minutes = 60 ]
                then
                    ((hour++))
                    echo "Hour: $hour"
                    
            else
                echo "$minutes"
            fi
            ((minutes++))
        done
done