#!/usr/bin/env bash
# Modify Nginx configuration file to run as nginx user and listen on port 8080

sed -i 's/user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen .*/listen 8080;/g' /etc/nginx/nginx.conf
service nginx restart